name: Deploy Frontend to EC2

on:
  push:
    branches:
      - add_backend_logic

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build frontend
      run: npm run build

    - name: Clean old files on EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          rm -rf /home/ec2-user/frontend/*
          mkdir -p /home/ec2-user/frontend/

    - name: Upload build to EC2
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist/*"
        target: "/home/ec2-user/frontend/"

    - name: Deploy to Nginx webroot
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # 清空 nginx 的静态根目录
          sudo rm -rf /usr/share/nginx/html/*
          # 将最新 build 从 staging 目录同步过去
          sudo cp -r /home/ec2-user/frontend/* /usr/share/nginx/html/
          # （可选）修正权限
          sudo chown -R nginx:nginx /usr/share/nginx/html
          # 验证并重载 nginx
          sudo nginx -t
          sudo systemctl reload nginx
        
    - name: Check dist contents
      run: ls -lah dist/

